atproto-browser:
  - changed-files:
      - any-glob-to-any-file: packages/atproto-browser/**

frontpage:
  - changed-files:
      - any-glob-to-any-file: packages/frontpage/**

drainpipe:
  - changed-files:
      - any-glob-to-any-file: packages-rs/**

infra:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**
          - packages/frontpage/local-infra/**

documentation:
  - changed-files:
      - any-glob-to-any-file: "**/*.md"

enhancement:
  - head-branch: ["^feature", "feature", "^feat", "feat"]

fix:
  - head-branch: ["^fix", "fix"]
