atproto-browser:
  - changed-files:
      - any-glob-to-any-file: apps/atproto-browser/**

frontpage:
  - changed-files:
      - any-glob-to-any-file: apps/frontpage/**

drainpipe:
  - changed-files:
      - any-glob-to-any-file:
          - "{apps,packages}/drainpipe*/**"
          - packages/jetstream/**

infra:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**
          - apps/frontpage/local-infra/**

documentation:
  - changed-files:
      - any-glob-to-any-file: "**/*.md"

enhancement:
  - head-branch: ["^feature", "feature", "^feat", "feat"]

fix:
  - head-branch: ["^fix", "fix"]
